'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
<Assembly: AssemblyCompany("Outercurve Foundation"),  _
 Assembly: AssemblyCopyright("Copyright © 2015 Outercurve Foundation."),  _
 Assembly: AssemblyVersion("2.1.0.1"),  _
 Assembly: AssemblyFileVersion("2.1.0.1"),  _
 Assembly: AssemblyInformationalVersion("2.1.0")> 

