//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("Outercurve Foundation")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2015 Outercurve Foundation.")]
[assembly: System.Reflection.AssemblyVersion("2.1.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.1.0")]


