//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("IT Solutions Roland Breitschaft")]
[assembly: AssemblyCopyright("Copyright © 2015 IT Solutions Roland Breitschaft.")]
[assembly: AssemblyVersion("2.1.0.924")]
[assembly: AssemblyFileVersion("2.1.0.924")]
[assembly: AssemblyInformationalVersion("2.1.0")]


