//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.8662
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
using WebsitePanel.ResultObjects;


namespace WebsitePanel.AutoDiscovery
{
	using System.Xml.Serialization;
	using System.Web.Services;
	using System.ComponentModel;
	using System.Web.Services.Protocols;
	using System;
	using System.Diagnostics;

    
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("wsdl", "2.0.50727.42")]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	[System.Web.Services.WebServiceBindingAttribute (Name = "AutoDiscoverySoap", Namespace = "http://tempuri.org/")]
	[System.Xml.Serialization.XmlIncludeAttribute (typeof(ResultObject))]
	public partial class AutoDiscovery : Microsoft.Web.Services3.WebServicesClientProtocol
	{
        
		private System.Threading.SendOrPostCallback IsInstalledOperationCompleted;
        
		private System.Threading.SendOrPostCallback GetServerVersionOperationCompleted;

		/// <remarks/>
		public AutoDiscovery ()
		{
			this.Url = "http://localhost:9003/AutoDiscovery.asmx";
		}

		/// <remarks/>
		public event IsInstalledCompletedEventHandler IsInstalledCompleted;
        
		/// <remarks/>
		public event GetServerVersionCompletedEventHandler GetServerVersionCompleted;

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute ("http://tempuri.org/IsInstalled", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public BoolResult IsInstalled (string providerName)
		{
			object[] results = this.Invoke ("IsInstalled", new object[] {
				providerName
			});
			return ((BoolResult)(results [0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginIsInstalled (string providerName, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke ("IsInstalled", new object[] {
				providerName
			}, callback, asyncState);
		}

		/// <remarks/>
		public BoolResult EndIsInstalled (System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke (asyncResult);
			return ((BoolResult)(results [0]));
		}

		/// <remarks/>
		public void IsInstalledAsync (string providerName)
		{
			this.IsInstalledAsync (providerName, null);
		}

		/// <remarks/>
		public void IsInstalledAsync (string providerName, object userState)
		{
			if ((this.IsInstalledOperationCompleted == null)) {
				this.IsInstalledOperationCompleted = new System.Threading.SendOrPostCallback (this.OnIsInstalledOperationCompleted);
			}
			this.InvokeAsync ("IsInstalled", new object[] {
				providerName
			}, this.IsInstalledOperationCompleted, userState);
		}

		private void OnIsInstalledOperationCompleted (object arg)
		{
			if ((this.IsInstalledCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.IsInstalledCompleted (this, new IsInstalledCompletedEventArgs (invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute ("http://tempuri.org/GetServerVersion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string GetServerVersion ()
		{
			object[] results = this.Invoke ("GetServerVersion", new object[0]);
			return ((string)(results [0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetServerVersion (System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke ("GetServerVersion", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public string EndGetServerVersion (System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke (asyncResult);
			return ((string)(results [0]));
		}

		/// <remarks/>
		public void GetServerVersionAsync ()
		{
			this.GetServerVersionAsync (null);
		}

		/// <remarks/>
		public void GetServerVersionAsync (object userState)
		{
			if ((this.GetServerVersionOperationCompleted == null)) {
				this.GetServerVersionOperationCompleted = new System.Threading.SendOrPostCallback (this.OnGetServerVersionOperationCompleted);
			}
			this.InvokeAsync ("GetServerVersion", new object[0], this.GetServerVersionOperationCompleted, userState);
		}

		private void OnGetServerVersionOperationCompleted (object arg)
		{
			if ((this.GetServerVersionCompleted != null)) {
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.GetServerVersionCompleted (this, new GetServerVersionCompletedEventArgs (invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		public new void CancelAsync (object userState)
		{
			base.CancelAsync (userState);
		}
	}
    
	/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("wsdl", "2.0.50727.42")]
    public delegate void IsInstalledCompletedEventHandler (object sender, IsInstalledCompletedEventArgs e);
    
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("wsdl", "2.0.50727.42")]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	public partial class IsInstalledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{
        
		private object[] results;

		internal IsInstalledCompletedEventArgs (object[] results, System.Exception exception, bool cancelled, object userState) :
			base (exception, cancelled, userState)
		{
			this.results = results;
		}

		/// <remarks/>
		public BoolResult Result {
			get {
				this.RaiseExceptionIfNecessary ();
				return ((BoolResult)(this.results [0]));
			}
		}
	}
    
	/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute ("wsdl", "2.0.50727.42")]
    public delegate void GetServerVersionCompletedEventHandler (object sender, GetServerVersionCompletedEventArgs e);
    
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("wsdl", "2.0.50727.42")]
	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.ComponentModel.DesignerCategoryAttribute ("code")]
	public partial class GetServerVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{
        
		private object[] results;

		internal GetServerVersionCompletedEventArgs (object[] results, System.Exception exception, bool cancelled, object userState) :
			base (exception, cancelled, userState)
		{
			this.results = results;
		}

		/// <remarks/>
		public string Result {
			get {
				this.RaiseExceptionIfNecessary ();
				return ((string)(this.results [0]));
			}
		}
	}
}
